### ISSUE TITLE
music folder not indexed

### ISSUE THREAD

**Issue by monperrus** [Deaftone/Deaftone#18]
Hi,

I can successfully run deaftone but the music folder set in `settings.toml` is not indexed.

```
$ curl http://localhost:3030/artists
{"data":[]}
```

how to fix this?

thanks!

**Comment by monperrus** [comment]
Thanks for your answer.

```
$ curl "http://localhost:3030/tasks?task=scan_library"
{"status":"sent"}
```

however, nothing happens after, the albums/artists endpoints are still empty.

I have triple-checked `media_path="/home/Musique/"` and I don't see anything in the log.

**Comment by 112RG** [comment]
Currently it only scans flac files also are you trying to scan mp3's?

**Comment by monperrus** [comment]
Yes! Thanks for the explanation.

See https://github.com/Deaftone/Deaftone/pull/19
